services:
  postgres:
    image: postgres:17.3
    container_name: vast-bricks-postgres
    environment:
      POSTGRES_USER: bricks
      POSTGRES_PASSWORD: bricks
      POSTGRES_DB: bricks
      PGDATA: /postgres-data
      TZ: Europe/Riga
    volumes:
      - postgres-vast-bricks:/postgres-data
    ports:
      - target: 5432
        published: 2345
    shm_size: '256mb'
    command: ["postgres", "-c", "log_statement=all", "-c", "shared_preload_libraries=pg_stat_statements"]

  tor-proxy:
    image: dperson/torproxy
    container_name: vast-bricks-tor-proxy
    ports:
      - target: 9050
        published: 9050
        host_ip: 127.0.0.1
      - target: 8118
        published: 8118
        host_ip: 127.0.0.1
      - target: 9051
        published: 9051
        host_ip: 127.0.0.1
    command: ["-p", "yourpass"]

  wiremock:
    image: wiremock/wiremock:3.13.2
    container_name: vast-bricks-wiremock
    ports:
      - target: 8080
        published: 9010
        host_ip: 127.0.0.1

volumes:
  postgres-vast-bricks:
