package com.vastbricks.integration.bricklink;

import com.fasterxml.jackson.dataformat.xml.XmlFactory;
import com.fasterxml.jackson.dataformat.xml.XmlMapper;
import com.vastbricks.market.link.TorRestTemplate;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.apache.commons.lang3.StringUtils;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Component;
import org.springframework.web.client.HttpStatusCodeException;
import org.springframework.web.client.RestClientException;
import org.springframework.web.client.RestTemplate;

import javax.xml.stream.XMLInputFactory;
import java.io.IOException;
import java.net.URI;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.function.Function;
import java.util.function.Supplier;

@Component
@RequiredArgsConstructor
public class LinkInternalClient {
    private static final LinkAuthenticationMode[] AUTHENTICATION_MODES = {
        LinkAuthenticationMode.TOKEN,
        LinkAuthenticationMode.SESSION_COOKIE
    };
    private static final LinkRestTemplateMode REST_TEMPLATE_MODE = LinkRestTemplateMode.SIMPLE;
    private static final URI ORDER_EXPORT_URI = URI.create("https://www.bricklink.com/orderExcelFinal.asp");
    private static final URI VAT_INVOICE_URI = URI.create("https://www.bricklink.com/_file/orders/vat_invoice.file");

    private final LinkCredentialService credentialService;
    private final LinkTokenAuthenticator tokenAuthenticator;
    private final TorRestTemplate sessionRestTemplate = new TorRestTemplate(true, HttpStatus.FORBIDDEN);
    private final TorRestTemplate tokenRestTemplate = new TorRestTemplate(HttpStatus.METHOD_NOT_ALLOWED, HttpStatus.FORBIDDEN);
    private final RestTemplate simpleRestTemplate = new RestTemplate();
    private final URI orderExportUri = ORDER_EXPORT_URI;
    private final XmlMapper xmlMapper = createXmlMapper();

    /**
     * Downloads BrickLink's XML order export. An empty array means BrickLink reported no matching orders.
     */
    public byte[] exportOrders(OrderExportRequest request) {
        if (request == null) {
            throw new IllegalArgumentException("request is required");
        }

        return executeWithAuthentication(
            "BrickLink order export",
            mode -> sendOrderExport(request, mode),
            this::bodyOrThrow
        );
    }

    /**
     * Downloads and parses BrickLink's XML order-summary export.
     */
    public List<LinkOrderSummary> listOrders(OrderExportRequest request) {
        validateOrderListRequest(request);
        return executeWithAuthentication(
            "BrickLink order list",
            mode -> sendOrderExport(request, mode),
            response -> parseOrderExport(bodyOrThrow(response))
        );
    }

    /**
     * Downloads the VAT invoice generated by BrickLink for an order.
     */
    public byte[] downloadVatInvoice(long orderId) {
        if (orderId <= 0) {
            throw new IllegalArgumentException("orderId must be positive");
        }

        return executeWithAuthentication(
            "BrickLink VAT invoice download for order " + orderId,
            mode -> sendVatInvoice(orderId, mode),
            response -> vatInvoiceBodyOrThrow(response, orderId)
        );
    }

    private <T> T executeWithAuthentication(
        String requestName,
        Function<LinkAuthenticationMode, LinkResponse> request,
        Function<LinkResponse, T> responseBody
    ) {
        var failures = new ArrayList<String>();
        for (var mode : AUTHENTICATION_MODES) {
            try {
                return responseBody.apply(request.apply(mode));
            } catch (LinkInternalClientException ex) {
                failures.add(mode + " failed: " + ex.getMessage());
            }
        }

        throw new LinkInternalClientException(
            requestName + " failed for all authentication modes. " + String.join("; ", failures)
        );
    }

    private void validateOrderListRequest(OrderExportRequest request) {
        if (request == null) {
            throw new IllegalArgumentException("request is required");
        }
        if (!"X".equalsIgnoreCase(request.getViewType())) {
            throw new IllegalArgumentException("viewType must be X for an XML order export");
        }
    }

    private List<LinkOrderSummary> parseOrderExport(byte[] xml) {
        if (xml.length == 0) {
            return List.of();
        }
        try {
            var export = xmlMapper.readValue(xml, LinkOrderExport.class);
            return export.getOrders() == null ? List.of() : List.copyOf(export.getOrders());
        } catch (IOException ex) {
            throw new LinkInternalClientException("Could not parse BrickLink order export XML", ex);
        }
    }

    private LinkResponse sendOrderExport(OrderExportRequest request, LinkAuthenticationMode mode) {
        return switch (mode) {
            case SESSION_COOKIE -> sendOrderExportWithSessionCookie(request);
            case TOKEN -> sendOrderExportWithToken(request);
        };
    }

    private LinkResponse sendOrderExportWithSessionCookie(OrderExportRequest orderRequest) {
        var cookie = credentialService.findValue(LinkCredentialType.SESSION_COOKIE)
            .orElseThrow(() -> new LinkAuthenticationException("BrickLink session cookie is not configured"));

        var headers = new HttpHeaders();
        headers.add(HttpHeaders.COOKIE, cookie);
        headers.add(HttpHeaders.CONTENT_TYPE, "application/x-www-form-urlencoded");
        return postOrderExport(orderRequest, headers, sessionRestTemplate);
    }

    private LinkResponse sendOrderExportWithToken(OrderExportRequest orderRequest) {
        var token = tokenAuthenticator.getOrCreateSessionToken();
        var response = sendOrderExportWithSessionToken(orderRequest, token);
        if (authenticationExpired(response)) {
            tokenAuthenticator.invalidateSessionToken(token);
            response = sendOrderExportWithSessionToken(orderRequest, tokenAuthenticator.getOrCreateSessionToken());
        }
        return response;
    }

    private LinkResponse sendOrderExportWithSessionToken(OrderExportRequest orderRequest, String token) {
        var headers = new HttpHeaders();
        headers.add(HttpHeaders.CONTENT_TYPE, "application/x-www-form-urlencoded");
        headers.add(LinkTokenAuthenticator.CLIENT_ID_HEADER, LinkTokenAuthenticator.CLIENT_ID);
        headers.add(LinkTokenAuthenticator.SESSION_TOKEN_HEADER, token);
        return postOrderExport(orderRequest, headers, tokenRestTemplate);
    }

    private LinkResponse postOrderExport(
        OrderExportRequest orderRequest,
        HttpHeaders headers,
        TorRestTemplate torRestTemplate
    ) {
        return exchange(
            () -> exchange(
                orderExportUri.toString(),
                HttpMethod.POST,
                new HttpEntity<>(formBody(orderRequest), headers),
                torRestTemplate
            ),
            "BrickLink order export request failed"
        );
    }

    private LinkResponse sendVatInvoice(long orderId, LinkAuthenticationMode mode) {
        return switch (mode) {
            case SESSION_COOKIE -> sendVatInvoiceWithSessionCookie(orderId);
            case TOKEN -> sendVatInvoiceWithToken(orderId);
        };
    }

    private LinkResponse sendVatInvoiceWithSessionCookie(long orderId) {
        var cookie = credentialService.findValue(LinkCredentialType.SESSION_COOKIE)
            .orElseThrow(() -> new LinkAuthenticationException("BrickLink session cookie is not configured"));

        var headers = new HttpHeaders();
        headers.add(HttpHeaders.ACCEPT, "application/pdf");
        headers.add(HttpHeaders.COOKIE, cookie);
        return getVatInvoice(orderId, headers, sessionRestTemplate);
    }

    private LinkResponse sendVatInvoiceWithToken(long orderId) {
        var token = tokenAuthenticator.getOrCreateSessionToken();
        var response = sendVatInvoiceWithSessionToken(orderId, token);
        if (authenticationExpired(response)) {
            tokenAuthenticator.invalidateSessionToken(token);
            response = sendVatInvoiceWithSessionToken(orderId, tokenAuthenticator.getOrCreateSessionToken());
        }
        return response;
    }

    private LinkResponse sendVatInvoiceWithSessionToken(long orderId, String token) {
        var headers = new HttpHeaders();
        headers.add(HttpHeaders.ACCEPT, "application/pdf");
        headers.add(LinkTokenAuthenticator.CLIENT_ID_HEADER, LinkTokenAuthenticator.CLIENT_ID);
        headers.add(LinkTokenAuthenticator.SESSION_TOKEN_HEADER, token);
        return getVatInvoice(orderId, headers, tokenRestTemplate);
    }

    private LinkResponse getVatInvoice(
        long orderId,
        HttpHeaders headers,
        TorRestTemplate torRestTemplate
    ) {
        var uri = URI.create(VAT_INVOICE_URI + "?oid=" + orderId + "&type=I");
        return exchange(
            () -> exchange(
                uri.toString(),
                HttpMethod.GET,
                new HttpEntity<Void>(headers),
                torRestTemplate
            ),
            "BrickLink VAT invoice download failed for order " + orderId
        );
    }

    private ResponseEntity<byte[]> exchange(
        String url,
        HttpMethod method,
        HttpEntity<?> requestEntity,
        TorRestTemplate torRestTemplate
    ) {
        return switch (REST_TEMPLATE_MODE) {
            case SIMPLE -> simpleRestTemplate.exchange(url, method, requestEntity, byte[].class);
            case TOR -> torRestTemplate.exchange(url, method, requestEntity, byte[].class);
        };
    }

    private LinkResponse exchange(Supplier<ResponseEntity<byte[]>> request, String failureMessage) {
        try {
            var response = request.get();
            return new LinkResponse(response.getStatusCode().value(), response.getHeaders(), response.getBody());
        } catch (HttpStatusCodeException ex) {
            var responseHeaders = ex.getResponseHeaders() == null ? new HttpHeaders() : ex.getResponseHeaders();
            return new LinkResponse(ex.getStatusCode().value(), responseHeaders, ex.getResponseBodyAsByteArray());
        } catch (RestClientException ex) {
            throw new LinkInternalClientException(failureMessage, ex);
        }
    }

    private byte[] bodyOrThrow(LinkResponse response) {
        if (isEmptyOrderExport(response)) {
            return new byte[0];
        }
        if (response.statusCode < 200 || response.statusCode >= 300) {
            throw new LinkInternalClientException(
                "BrickLink order export failed with HTTP " + response.statusCode + redirectSuffix(response)
            );
        }
        return response.body;
    }

    private byte[] vatInvoiceBodyOrThrow(LinkResponse response, long orderId) {
        if (response.statusCode < 200 || response.statusCode >= 300) {
            throw new LinkInternalClientException(
                "BrickLink VAT invoice download failed for order " + orderId
                    + " with HTTP " + response.statusCode + redirectSuffix(response)
            );
        }
        if (response.body == null || response.body.length == 0) {
            throw new LinkInternalClientException(
                "BrickLink VAT invoice download returned an empty response for order " + orderId
            );
        }
        if (!isPdf(response.body)) {
            throw new LinkInternalClientException(
                "BrickLink VAT invoice download did not return a PDF for order " + orderId
            );
        }
        return response.body;
    }

    private boolean isPdf(byte[] body) {
        var signature = new byte[] {'%', 'P', 'D', 'F', '-'};
        var searchLength = Math.min(body.length, 1024);
        for (var offset = 0; offset <= searchLength - signature.length; offset++) {
            var matches = true;
            for (var index = 0; index < signature.length; index++) {
                if (body[offset + index] != signature[index]) {
                    matches = false;
                    break;
                }
            }
            if (matches) {
                return true;
            }
        }
        return false;
    }

    private String formBody(OrderExportRequest request) {
        var fields = new LinkedHashMap<String, String>();
        putIfNotBlank(fields, "action", request.getAction());
        fields.put("orderType", request.getOrderType().name().toLowerCase(Locale.ROOT));
        putIfNotBlank(fields, "viewType", request.getViewType());
        putIfNotBlank(fields, "getStatusSel", request.getGetStatusSel());
        putIfNotBlank(fields, "getFiled", request.getGetFiled());
        putIfNotBlank(fields, "getDetail", request.getGetDetail());
        putIfNotBlank(fields, "getDateFormat", request.getGetDateFormat());
        putIfNotBlank(fields, "useRealName", request.getUseRealName());
        putIfNotBlank(fields, "includeMyCost", request.getIncludeMyCost());

        if (request.getFromDate() != null) {
            putIfNotBlank(fields, "getOrders", request.getGetOrders());
            addDate(fields, "f", request.getFromDate());
            addDate(fields, "t", request.getToDate());
        } else if (request.getOrderId() != null) {
            fields.put("orderID", request.getOrderId());
        }

        return fields.entrySet().stream()
            .map(entry -> encode(entry.getKey()) + "=" + encode(entry.getValue()))
            .collect(java.util.stream.Collectors.joining("&"));
    }

    private void putIfNotBlank(Map<String, String> fields, String name, String value) {
        if (StringUtils.isNotBlank(value)) {
            fields.put(name, value);
        }
    }

    private void addDate(Map<String, String> fields, String prefix, LocalDate date) {
        fields.put(prefix + "MM", Integer.toString(date.getMonthValue()));
        fields.put(prefix + "DD", Integer.toString(date.getDayOfMonth()));
        fields.put(prefix + "YY", Integer.toString(date.getYear()));
    }

    private String encode(String value) {
        return URLEncoder.encode(value, StandardCharsets.UTF_8);
    }

    private boolean authenticationExpired(LinkResponse response) {
        if (response.statusCode == 401) {
            return true;
        }
        return response.statusCode == 302
            && response.headers.getFirst(HttpHeaders.LOCATION) != null
            && response.headers.getFirst(HttpHeaders.LOCATION)
            .contains("auth/sign-in?");
    }

    private boolean isEmptyOrderExport(LinkResponse response) {
        return response.statusCode == 302
            && response.headers.getFirst(HttpHeaders.LOCATION) != null
            && response.headers.getFirst(HttpHeaders.LOCATION)
            .contains("error=EOF");
    }

    private String redirectSuffix(LinkResponse response) {
        var location = response.headers.getFirst(HttpHeaders.LOCATION);
        return location == null ? "" : ", redirecting to " + location;
    }

    private static XmlMapper createXmlMapper() {
        var inputFactory = XMLInputFactory.newFactory();
        inputFactory.setProperty(XMLInputFactory.SUPPORT_DTD, false);
        inputFactory.setProperty("javax.xml.stream.isSupportingExternalEntities", false);
        return new XmlMapper(new XmlFactory(inputFactory));
    }

    @Getter
    @AllArgsConstructor
    private static class LinkResponse {
        private final int statusCode;
        private final HttpHeaders headers;
        private final byte[] body;
    }
}
