services:
  postgres:
    image: postgres:17.3
    container_name: vast-bricks-postgres
    environment:
      POSTGRES_USER: bricks
      POSTGRES_PASSWORD: bricks
      POSTGRES_DB: bricks
      PGDATA: /postgres-data
      TZ: Europe/Riga
    volumes:
      - postgres-vast-bricks:/postgres-data
    ports:
      - target: 5432
        published: 2345
    shm_size: '256mb'
    command: ["postgres", "-c", "log_statement=all", "-c", "shared_preload_libraries=pg_stat_statements"]

volumes:
  postgres-vast-bricks:
