-- The store's own orders, imported from the order archive.
--
-- Every field the reconciliation report states about an order itself, under the same names, so the two screens can
-- be read against each other without a reader translating between them. What is not here is what the other sources
-- report on an order - the payment gateway, the post office, the accounting invoice - which reconciliation collects
-- live and stores nowhere.
CREATE TABLE orders
(
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT      NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    source          VARCHAR(20) NOT NULL,
    order_id        VARCHAR(50) NOT NULL,
    order_date      TIMESTAMPTZ NOT NULL,
    buyer           VARCHAR(255),
    buyer_username  VARCHAR(255),
    lot_count       INTEGER,
    item_count      INTEGER,
    payment_method  VARCHAR(100),
    currency        VARCHAR(3),
    tax_type        VARCHAR(30),
    facilitator_tax NUMERIC(19, 2),
    sub_total       NUMERIC(19, 2),
    shipping_cost   NUMERIC(19, 2),
    grand_total     NUMERIC(19, 2),
    refunded_amount NUMERIC(19, 2),
    archived_at     TIMESTAMPTZ NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- What makes a re-imported order the same order. Tenant-owned tables carry the tenant in their unique constraints:
-- @TenantId keeps one tenant from reading another's rows, but two stores legitimately hold the same marketplace
-- order id, and that collision is the one thing the annotation does not catch. The source is in it because BrickLink
-- and BrickOwl number their orders independently.
CREATE UNIQUE INDEX orders_source_order_id_unique ON orders (tenant_id, source, order_id);

CREATE INDEX orders_order_date ON orders (tenant_id, order_date);

COMMENT ON TABLE orders IS
    'A marketplace order, as the order archive last held it. Imported from the archived files rather than from the marketplace, so what is stored is always something the store has its own copy of.';
COMMENT ON COLUMN orders.source IS
    'The marketplace the order was placed on: BRICKLINK or BRICKOWL. An order id only identifies an order beside it.';
COMMENT ON COLUMN orders.order_id IS
    'The marketplace''s own order id. Text rather than a number because BrickOwl states one and BrickLink the other, and neither is arithmetic.';
COMMENT ON COLUMN orders.buyer IS
    'The buyer''s own name. BrickLink states it only in the accounting export, which is one of the reasons that export is what the import reads first.';
COMMENT ON COLUMN orders.buyer_username IS
    'The buyer''s account with the marketplace. BrickLink states it only in its API record of the order, so an order reads both files to name a buyer both ways.';
COMMENT ON COLUMN orders.payment_method IS
    'How the order was paid, unified across the marketplaces'' wordings so an order paid the same way reads the same whichever it came from.';
COMMENT ON COLUMN orders.currency IS
    'What the buyer paid in, as the marketplace stated it. The amounts beside it are in the store''s own base currency, which is how the reconciliation report states them too.';
COMMENT ON COLUMN orders.tax_type IS
    'How the order is treated for tax, derived from what the marketplace reported. Null where the archive holds no file that states enough to type it.';
COMMENT ON COLUMN orders.facilitator_tax IS
    'What the marketplace collected on the order as tax facilitator, or null where it collected none.';
COMMENT ON COLUMN orders.shipping_cost IS
    'What the marketplace charged the buyer for shipping. The buyer''s side of the postage, not the post office''s.';
COMMENT ON COLUMN orders.grand_total IS
    'The order total in the store''s own base currency, as the marketplace stated it: BrickLink''s BASEGRANDTOTAL, BrickOwl''s base_order_total.';
COMMENT ON COLUMN orders.refunded_amount IS
    'What the marketplace reports was refunded, or null where it reports none. BrickLink states it only on the order detail page, which is the third file the archive keeps.';
COMMENT ON COLUMN orders.archived_at IS
    'The moment the imported files are the archive of - when the marketplace last stated the order changed. What makes the import an upsert: files naming a later moment than this replace the row, and ones naming this moment or an earlier one leave it alone.';
