CREATE TABLE api_keys
(
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    tenant_id    BIGINT       NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    name         VARCHAR(200) NOT NULL,
    token_hash   CHAR(64)     NOT NULL,
    token_prefix VARCHAR(20)  NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    expires_at   TIMESTAMPTZ,
    last_used_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX api_keys_token_hash_unique ON api_keys (token_hash);
CREATE UNIQUE INDEX api_keys_owner_name_unique ON api_keys (user_id, tenant_id, LOWER(name));
CREATE INDEX api_keys_owner ON api_keys (user_id, tenant_id, id);

COMMENT ON TABLE api_keys IS
    'A long-lived credential a user generates for an external program - a browser extension, BrickSync - to call the API without a login. Identity rather than tenant-owned data, for the same reason user_tenants is: the key is what a request is read against to decide its tenant, so filtering it by the tenant would need the answer it exists to give. Every management query scopes itself to the serving tenant and the calling user explicitly.';
COMMENT ON COLUMN api_keys.user_id IS
    'Who generated it. A key authenticates as its issuing user, so it can reach exactly what that user could and no more.';
COMMENT ON COLUMN api_keys.tenant_id IS
    'The one store this key serves. Stated when the key is generated rather than chosen per request, because the program presenting it has no login to select a tenant with.';
COMMENT ON COLUMN api_keys.token_hash IS
    'SHA-256 of the presented secret, hex. The secret itself is returned once at generation and stored nowhere, so a leaked table yields no usable key. Plain SHA-256 rather than a password hash is enough because the secret is 256 random bits, not something a person chose.';
COMMENT ON COLUMN api_keys.token_prefix IS
    'The opening characters of the secret, kept in clear so a list of keys can be told apart by the same fragment the external program shows.';
COMMENT ON COLUMN api_keys.expires_at IS
    'When the key stops authenticating. Null never expires, which is what an unattended program normally needs.';
COMMENT ON COLUMN api_keys.last_used_at IS
    'When a request last presented this key, so a key nothing uses any more can be recognised and revoked. Written at most once a minute rather than on every request.';
