-- What Latvijas Pasts charges to post a shipment, by destination, shipment type, service and weight band.
--
-- The first table of the rewrite with no tenant_id, and deliberately so. A tariff is a published price list: it is
-- identical for every store, it is fetched with no credential from a public endpoint, and it belongs to no tenant.
-- Stamping it per tenant would buy a duplicate of these rows per store, and a duplicate sweep to fill them, to
-- protect what anybody can read on a web page.
CREATE TABLE shipping_prices
(
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_code  VARCHAR(10)  NOT NULL,
    country_name  VARCHAR(255) NOT NULL,
    shipment_type VARCHAR(20)  NOT NULL,
    service       VARCHAR(20)  NOT NULL,
    weight_from_g INTEGER      NOT NULL,
    weight_to_g   INTEGER      NOT NULL,
    base_price    NUMERIC(19, 2) NOT NULL,
    tracking_fee  NUMERIC(19, 2) NOT NULL DEFAULT 0,
    currency      VARCHAR(3)   NOT NULL DEFAULT 'EUR',
    valid_from    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    valid_to      TIMESTAMPTZ,
    checked_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- One current price per band. History is rows whose valid_to is set, so the constraint holds only over the open
-- ones: a band whose price changed legitimately has a closed row and an open row for the same four columns.
CREATE UNIQUE INDEX shipping_prices_current_unique
    ON shipping_prices (country_code, shipment_type, service, weight_to_g)
    WHERE valid_to IS NULL;

-- How the screen reads it: one country, its open rows, in weight order.
CREATE INDEX shipping_prices_country_current
    ON shipping_prices (country_code, weight_to_g)
    WHERE valid_to IS NULL;

COMMENT ON TABLE shipping_prices IS
    'Latvijas Pasts postage by destination and weight band, swept from the public mans.pasts.lv calculator. Global rather than tenant-owned: a published tariff is the same price for every store and is reached with no credential.';
COMMENT ON COLUMN shipping_prices.country_code IS
    'The provider''s own destination code. Mostly ISO-3166 alpha-2, but not always: a territory priced apart from its mainland carries a numeric code of the provider''s own, so this is wider than two characters and is not a country_code anyone should join to blindly.';
COMMENT ON COLUMN shipping_prices.shipment_type IS
    'SMALL_PACKET for the tariff book''s Sikpaka, up to 2 kg, or PARCEL for its Paka above that.';
COMMENT ON COLUMN shipping_prices.service IS
    'ECONOMY (vienkarss) or STANDARD (izsekojams) under SMALL_PACKET; STANDARD_PLUS (ierakstits) under PARCEL, which is the only service Latvijas Pasts sells for a parcel.';
COMMENT ON COLUMN shipping_prices.weight_from_g IS
    'The lightest weight this price covers, in grams, inclusive. Zero for the first band.';
COMMENT ON COLUMN shipping_prices.weight_to_g IS
    'The heaviest weight this price covers, in grams, inclusive. Part of the key, the bands of one type being distinguished by nothing else.';
COMMENT ON COLUMN shipping_prices.base_price IS
    'The weight cost alone, as the provider states it. For ECONOMY this is the whole price; for STANDARD the tracking fee is added to it.';
COMMENT ON COLUMN shipping_prices.tracking_fee IS
    'What tracking costs on top of the base, stated separately by the provider and kept separately here so a tariff change says which half moved. Zero where the service carries no tracking charge.';
COMMENT ON COLUMN shipping_prices.valid_from IS
    'When this price was first seen. A sweep that confirms a price it already holds does not move it.';
COMMENT ON COLUMN shipping_prices.valid_to IS
    'When a later sweep found a different price, or null while this is the current one. History is how the table answers what an order cost at the time it shipped.';
COMMENT ON COLUMN shipping_prices.checked_at IS
    'When a sweep last confirmed this price is still what the provider states. Also what the job reads to decide whether the table is fresh enough to leave alone.';
