-- What the European Central Bank states one euro buys of another currency, on the day it published that rate.
--
-- No tenant_id, like shipping_prices before it: an ECB reference rate is published once for the whole world, is
-- fetched with no credential, and belongs to no tenant.
CREATE TABLE currency_rates
(
    id         BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency   VARCHAR(3)     NOT NULL,
    rate_date  DATE           NOT NULL,
    rate       NUMERIC(19, 6) NOT NULL,
    fetched_at TIMESTAMPTZ    NOT NULL DEFAULT now()
);

-- One row per currency per published day. The ECB never revises a day once it has stated it, so a sync that runs
-- again before the next publication finds the day already stored and writes nothing, rather than colliding here.
CREATE UNIQUE INDEX currency_rates_currency_date_unique
    ON currency_rates (currency, rate_date);

-- How a reader asks for one currency's history, most recent first.
CREATE INDEX currency_rates_currency_date
    ON currency_rates (currency, rate_date DESC);

COMMENT ON TABLE currency_rates IS
    'Euro reference rates published daily by the European Central Bank. Global rather than tenant-owned: the rate is the same for every store and is fetched with no credential.';
COMMENT ON COLUMN currency_rates.currency IS
    'The ISO 4217 code of the quoted currency, e.g. USD. The base currency is always EUR, exactly as the ECB states it, so EUR itself is not a row and is not stored as a column of its own.';
COMMENT ON COLUMN currency_rates.rate_date IS
    'The date the ECB published this rate for, which is the reference date it states rather than the day the sync happened to run.';
COMMENT ON COLUMN currency_rates.rate IS
    'How much of the currency one euro bought on rate_date, exactly as the ECB stated it.';
COMMENT ON COLUMN currency_rates.fetched_at IS
    'When the sync stored this row. Read to decide whether a firing this soon after another is fresh enough to skip asking the ECB again.';
