-- Every country, so a marketplace's own wording of one - a name, a code, a native spelling - can be resolved to the
-- one this store means by it. Global rather than tenant-owned: a country is the same country for every store.
CREATE TABLE countries
(
    code         VARCHAR(2)  PRIMARY KEY,
    name         TEXT        NOT NULL,
    search_terms JSONB       NOT NULL
);

COMMENT ON TABLE countries IS
    'Every ISO 3166-1 country, seeded once from the JDK''s own locale data rather than fetched from anywhere. Global: a country belongs to no tenant, the same way a currency rate does not.';
COMMENT ON COLUMN countries.code IS
    'The ISO 3166-1 alpha-2 code, e.g. LV - the same code order.country and the marketplaces'' own APIs already state.';
COMMENT ON COLUMN countries.name IS
    'The country''s own English name, as the JDK''s locale data states it. Read by a person; a lookup matches against search_terms instead.';
COMMENT ON COLUMN countries.search_terms IS
    'Every spelling that resolves to this country - the name and the alpha-2 and alpha-3 codes to start, and whatever alias a real order is later found to state, such as a marketplace''s free-text location naming a country in its own language. Matched case-insensitively; there is no meaning to the order they are listed in.';

-- Seeded from java.util.Locale.getISOCountries(), which is the JDK's own copy of the ISO 3166-1 list, plus its
-- English display name and alpha-3 code for each. A country the JDK carries with no distinct alpha-3 code - none do
-- today - would be seeded with the name and the alpha-2 code alone.
INSERT INTO countries (code, name, search_terms) VALUES
    ('AD', 'Andorra', '["Andorra", "AD", "AND"]'),
    ('AE', 'United Arab Emirates', '["United Arab Emirates", "AE", "ARE"]'),
    ('AF', 'Afghanistan', '["Afghanistan", "AF", "AFG"]'),
    ('AG', 'Antigua & Barbuda', '["Antigua & Barbuda", "AG", "ATG"]'),
    ('AI', 'Anguilla', '["Anguilla", "AI", "AIA"]'),
    ('AL', 'Albania', '["Albania", "AL", "ALB"]'),
    ('AM', 'Armenia', '["Armenia", "AM", "ARM"]'),
    ('AO', 'Angola', '["Angola", "AO", "AGO"]'),
    ('AQ', 'Antarctica', '["Antarctica", "AQ", "ATA"]'),
    ('AR', 'Argentina', '["Argentina", "AR", "ARG"]'),
    ('AS', 'American Samoa', '["American Samoa", "AS", "ASM"]'),
    ('AT', 'Austria', '["Austria", "AT", "AUT"]'),
    ('AU', 'Australia', '["Australia", "AU", "AUS"]'),
    ('AW', 'Aruba', '["Aruba", "AW", "ABW"]'),
    ('AX', 'Åland Islands', '["Åland Islands", "AX", "ALA"]'),
    ('AZ', 'Azerbaijan', '["Azerbaijan", "AZ", "AZE"]'),
    ('BA', 'Bosnia & Herzegovina', '["Bosnia & Herzegovina", "BA", "BIH"]'),
    ('BB', 'Barbados', '["Barbados", "BB", "BRB"]'),
    ('BD', 'Bangladesh', '["Bangladesh", "BD", "BGD"]'),
    ('BE', 'Belgium', '["Belgium", "BE", "BEL"]'),
    ('BF', 'Burkina Faso', '["Burkina Faso", "BF", "BFA"]'),
    ('BG', 'Bulgaria', '["Bulgaria", "BG", "BGR"]'),
    ('BH', 'Bahrain', '["Bahrain", "BH", "BHR"]'),
    ('BI', 'Burundi', '["Burundi", "BI", "BDI"]'),
    ('BJ', 'Benin', '["Benin", "BJ", "BEN"]'),
    ('BL', 'St. Barthélemy', '["St. Barthélemy", "BL", "BLM"]'),
    ('BM', 'Bermuda', '["Bermuda", "BM", "BMU"]'),
    ('BN', 'Brunei', '["Brunei", "BN", "BRN"]'),
    ('BO', 'Bolivia', '["Bolivia", "BO", "BOL"]'),
    ('BQ', 'Caribbean Netherlands', '["Caribbean Netherlands", "BQ", "BES"]'),
    ('BR', 'Brazil', '["Brazil", "BR", "BRA"]'),
    ('BS', 'Bahamas', '["Bahamas", "BS", "BHS"]'),
    ('BT', 'Bhutan', '["Bhutan", "BT", "BTN"]'),
    ('BV', 'Bouvet Island', '["Bouvet Island", "BV", "BVT"]'),
    ('BW', 'Botswana', '["Botswana", "BW", "BWA"]'),
    ('BY', 'Belarus', '["Belarus", "BY", "BLR"]'),
    ('BZ', 'Belize', '["Belize", "BZ", "BLZ"]'),
    ('CA', 'Canada', '["Canada", "CA", "CAN"]'),
    ('CC', 'Cocos (Keeling) Islands', '["Cocos (Keeling) Islands", "CC", "CCK"]'),
    ('CD', 'Congo - Kinshasa', '["Congo - Kinshasa", "CD", "COD"]'),
    ('CF', 'Central African Republic', '["Central African Republic", "CF", "CAF"]'),
    ('CG', 'Congo - Brazzaville', '["Congo - Brazzaville", "CG", "COG"]'),
    ('CH', 'Switzerland', '["Switzerland", "CH", "CHE"]'),
    ('CI', 'Côte d’Ivoire', '["Côte d’Ivoire", "CI", "CIV"]'),
    ('CK', 'Cook Islands', '["Cook Islands", "CK", "COK"]'),
    ('CL', 'Chile', '["Chile", "CL", "CHL"]'),
    ('CM', 'Cameroon', '["Cameroon", "CM", "CMR"]'),
    ('CN', 'China', '["China", "CN", "CHN"]'),
    ('CO', 'Colombia', '["Colombia", "CO", "COL"]'),
    ('CR', 'Costa Rica', '["Costa Rica", "CR", "CRI"]'),
    ('CU', 'Cuba', '["Cuba", "CU", "CUB"]'),
    ('CV', 'Cape Verde', '["Cape Verde", "CV", "CPV"]'),
    ('CW', 'Curaçao', '["Curaçao", "CW", "CUW"]'),
    ('CX', 'Christmas Island', '["Christmas Island", "CX", "CXR"]'),
    ('CY', 'Cyprus', '["Cyprus", "CY", "CYP"]'),
    ('CZ', 'Czechia', '["Czechia", "CZ", "CZE"]'),
    ('DE', 'Germany', '["Germany", "DE", "DEU"]'),
    ('DJ', 'Djibouti', '["Djibouti", "DJ", "DJI"]'),
    ('DK', 'Denmark', '["Denmark", "DK", "DNK"]'),
    ('DM', 'Dominica', '["Dominica", "DM", "DMA"]'),
    ('DO', 'Dominican Republic', '["Dominican Republic", "DO", "DOM"]'),
    ('DZ', 'Algeria', '["Algeria", "DZ", "DZA"]'),
    ('EC', 'Ecuador', '["Ecuador", "EC", "ECU"]'),
    ('EE', 'Estonia', '["Estonia", "EE", "EST"]'),
    ('EG', 'Egypt', '["Egypt", "EG", "EGY"]'),
    ('EH', 'Western Sahara', '["Western Sahara", "EH", "ESH"]'),
    ('ER', 'Eritrea', '["Eritrea", "ER", "ERI"]'),
    ('ES', 'Spain', '["Spain", "ES", "ESP"]'),
    ('ET', 'Ethiopia', '["Ethiopia", "ET", "ETH"]'),
    ('FI', 'Finland', '["Finland", "FI", "FIN"]'),
    ('FJ', 'Fiji', '["Fiji", "FJ", "FJI"]'),
    ('FK', 'Falkland Islands', '["Falkland Islands", "FK", "FLK"]'),
    ('FM', 'Micronesia', '["Micronesia", "FM", "FSM"]'),
    ('FO', 'Faroe Islands', '["Faroe Islands", "FO", "FRO"]'),
    ('FR', 'France', '["France", "FR", "FRA"]'),
    ('GA', 'Gabon', '["Gabon", "GA", "GAB"]'),
    ('GB', 'United Kingdom', '["United Kingdom", "GB", "GBR"]'),
    ('GD', 'Grenada', '["Grenada", "GD", "GRD"]'),
    ('GE', 'Georgia', '["Georgia", "GE", "GEO"]'),
    ('GF', 'French Guiana', '["French Guiana", "GF", "GUF"]'),
    ('GG', 'Guernsey', '["Guernsey", "GG", "GGY"]'),
    ('GH', 'Ghana', '["Ghana", "GH", "GHA"]'),
    ('GI', 'Gibraltar', '["Gibraltar", "GI", "GIB"]'),
    ('GL', 'Greenland', '["Greenland", "GL", "GRL"]'),
    ('GM', 'Gambia', '["Gambia", "GM", "GMB"]'),
    ('GN', 'Guinea', '["Guinea", "GN", "GIN"]'),
    ('GP', 'Guadeloupe', '["Guadeloupe", "GP", "GLP"]'),
    ('GQ', 'Equatorial Guinea', '["Equatorial Guinea", "GQ", "GNQ"]'),
    ('GR', 'Greece', '["Greece", "GR", "GRC"]'),
    ('GS', 'South Georgia & South Sandwich Islands', '["South Georgia & South Sandwich Islands", "GS", "SGS"]'),
    ('GT', 'Guatemala', '["Guatemala", "GT", "GTM"]'),
    ('GU', 'Guam', '["Guam", "GU", "GUM"]'),
    ('GW', 'Guinea-Bissau', '["Guinea-Bissau", "GW", "GNB"]'),
    ('GY', 'Guyana', '["Guyana", "GY", "GUY"]'),
    ('HK', 'Hong Kong SAR China', '["Hong Kong SAR China", "HK", "HKG"]'),
    ('HM', 'Heard & McDonald Islands', '["Heard & McDonald Islands", "HM", "HMD"]'),
    ('HN', 'Honduras', '["Honduras", "HN", "HND"]'),
    ('HR', 'Croatia', '["Croatia", "HR", "HRV"]'),
    ('HT', 'Haiti', '["Haiti", "HT", "HTI"]'),
    ('HU', 'Hungary', '["Hungary", "HU", "HUN"]'),
    ('ID', 'Indonesia', '["Indonesia", "ID", "IDN"]'),
    ('IE', 'Ireland', '["Ireland", "IE", "IRL"]'),
    ('IL', 'Israel', '["Israel", "IL", "ISR"]'),
    ('IM', 'Isle of Man', '["Isle of Man", "IM", "IMN"]'),
    ('IN', 'India', '["India", "IN", "IND"]'),
    ('IO', 'British Indian Ocean Territory', '["British Indian Ocean Territory", "IO", "IOT"]'),
    ('IQ', 'Iraq', '["Iraq", "IQ", "IRQ"]'),
    ('IR', 'Iran', '["Iran", "IR", "IRN"]'),
    ('IS', 'Iceland', '["Iceland", "IS", "ISL"]'),
    ('IT', 'Italy', '["Italy", "IT", "ITA"]'),
    ('JE', 'Jersey', '["Jersey", "JE", "JEY"]'),
    ('JM', 'Jamaica', '["Jamaica", "JM", "JAM"]'),
    ('JO', 'Jordan', '["Jordan", "JO", "JOR"]'),
    ('JP', 'Japan', '["Japan", "JP", "JPN"]'),
    ('KE', 'Kenya', '["Kenya", "KE", "KEN"]'),
    ('KG', 'Kyrgyzstan', '["Kyrgyzstan", "KG", "KGZ"]'),
    ('KH', 'Cambodia', '["Cambodia", "KH", "KHM"]'),
    ('KI', 'Kiribati', '["Kiribati", "KI", "KIR"]'),
    ('KM', 'Comoros', '["Comoros", "KM", "COM"]'),
    ('KN', 'St. Kitts & Nevis', '["St. Kitts & Nevis", "KN", "KNA"]'),
    ('KP', 'North Korea', '["North Korea", "KP", "PRK"]'),
    ('KR', 'South Korea', '["South Korea", "KR", "KOR"]'),
    ('KW', 'Kuwait', '["Kuwait", "KW", "KWT"]'),
    ('KY', 'Cayman Islands', '["Cayman Islands", "KY", "CYM"]'),
    ('KZ', 'Kazakhstan', '["Kazakhstan", "KZ", "KAZ"]'),
    ('LA', 'Laos', '["Laos", "LA", "LAO"]'),
    ('LB', 'Lebanon', '["Lebanon", "LB", "LBN"]'),
    ('LC', 'St. Lucia', '["St. Lucia", "LC", "LCA"]'),
    ('LI', 'Liechtenstein', '["Liechtenstein", "LI", "LIE"]'),
    ('LK', 'Sri Lanka', '["Sri Lanka", "LK", "LKA"]'),
    ('LR', 'Liberia', '["Liberia", "LR", "LBR"]'),
    ('LS', 'Lesotho', '["Lesotho", "LS", "LSO"]'),
    ('LT', 'Lithuania', '["Lithuania", "LT", "LTU"]'),
    ('LU', 'Luxembourg', '["Luxembourg", "LU", "LUX"]'),
    ('LV', 'Latvia', '["Latvia", "LV", "LVA", "Latvija"]'),
    ('LY', 'Libya', '["Libya", "LY", "LBY"]'),
    ('MA', 'Morocco', '["Morocco", "MA", "MAR"]'),
    ('MC', 'Monaco', '["Monaco", "MC", "MCO"]'),
    ('MD', 'Moldova', '["Moldova", "MD", "MDA"]'),
    ('ME', 'Montenegro', '["Montenegro", "ME", "MNE"]'),
    ('MF', 'St. Martin', '["St. Martin", "MF", "MAF"]'),
    ('MG', 'Madagascar', '["Madagascar", "MG", "MDG"]'),
    ('MH', 'Marshall Islands', '["Marshall Islands", "MH", "MHL"]'),
    ('MK', 'North Macedonia', '["North Macedonia", "MK", "MKD"]'),
    ('ML', 'Mali', '["Mali", "ML", "MLI"]'),
    ('MM', 'Myanmar (Burma)', '["Myanmar (Burma)", "MM", "MMR"]'),
    ('MN', 'Mongolia', '["Mongolia", "MN", "MNG"]'),
    ('MO', 'Macao SAR China', '["Macao SAR China", "MO", "MAC"]'),
    ('MP', 'Northern Mariana Islands', '["Northern Mariana Islands", "MP", "MNP"]'),
    ('MQ', 'Martinique', '["Martinique", "MQ", "MTQ"]'),
    ('MR', 'Mauritania', '["Mauritania", "MR", "MRT"]'),
    ('MS', 'Montserrat', '["Montserrat", "MS", "MSR"]'),
    ('MT', 'Malta', '["Malta", "MT", "MLT"]'),
    ('MU', 'Mauritius', '["Mauritius", "MU", "MUS"]'),
    ('MV', 'Maldives', '["Maldives", "MV", "MDV"]'),
    ('MW', 'Malawi', '["Malawi", "MW", "MWI"]'),
    ('MX', 'Mexico', '["Mexico", "MX", "MEX"]'),
    ('MY', 'Malaysia', '["Malaysia", "MY", "MYS"]'),
    ('MZ', 'Mozambique', '["Mozambique", "MZ", "MOZ"]'),
    ('NA', 'Namibia', '["Namibia", "NA", "NAM"]'),
    ('NC', 'New Caledonia', '["New Caledonia", "NC", "NCL"]'),
    ('NE', 'Niger', '["Niger", "NE", "NER"]'),
    ('NF', 'Norfolk Island', '["Norfolk Island", "NF", "NFK"]'),
    ('NG', 'Nigeria', '["Nigeria", "NG", "NGA"]'),
    ('NI', 'Nicaragua', '["Nicaragua", "NI", "NIC"]'),
    ('NL', 'Netherlands', '["Netherlands", "NL", "NLD"]'),
    ('NO', 'Norway', '["Norway", "NO", "NOR"]'),
    ('NP', 'Nepal', '["Nepal", "NP", "NPL"]'),
    ('NR', 'Nauru', '["Nauru", "NR", "NRU"]'),
    ('NU', 'Niue', '["Niue", "NU", "NIU"]'),
    ('NZ', 'New Zealand', '["New Zealand", "NZ", "NZL"]'),
    ('OM', 'Oman', '["Oman", "OM", "OMN"]'),
    ('PA', 'Panama', '["Panama", "PA", "PAN"]'),
    ('PE', 'Peru', '["Peru", "PE", "PER"]'),
    ('PF', 'French Polynesia', '["French Polynesia", "PF", "PYF"]'),
    ('PG', 'Papua New Guinea', '["Papua New Guinea", "PG", "PNG"]'),
    ('PH', 'Philippines', '["Philippines", "PH", "PHL"]'),
    ('PK', 'Pakistan', '["Pakistan", "PK", "PAK"]'),
    ('PL', 'Poland', '["Poland", "PL", "POL"]'),
    ('PM', 'St. Pierre & Miquelon', '["St. Pierre & Miquelon", "PM", "SPM"]'),
    ('PN', 'Pitcairn Islands', '["Pitcairn Islands", "PN", "PCN"]'),
    ('PR', 'Puerto Rico', '["Puerto Rico", "PR", "PRI"]'),
    ('PS', 'Palestinian Territories', '["Palestinian Territories", "PS", "PSE"]'),
    ('PT', 'Portugal', '["Portugal", "PT", "PRT"]'),
    ('PW', 'Palau', '["Palau", "PW", "PLW"]'),
    ('PY', 'Paraguay', '["Paraguay", "PY", "PRY"]'),
    ('QA', 'Qatar', '["Qatar", "QA", "QAT"]'),
    ('RE', 'Réunion', '["Réunion", "RE", "REU"]'),
    ('RO', 'Romania', '["Romania", "RO", "ROU"]'),
    ('RS', 'Serbia', '["Serbia", "RS", "SRB"]'),
    ('RU', 'Russia', '["Russia", "RU", "RUS"]'),
    ('RW', 'Rwanda', '["Rwanda", "RW", "RWA"]'),
    ('SA', 'Saudi Arabia', '["Saudi Arabia", "SA", "SAU"]'),
    ('SB', 'Solomon Islands', '["Solomon Islands", "SB", "SLB"]'),
    ('SC', 'Seychelles', '["Seychelles", "SC", "SYC"]'),
    ('SD', 'Sudan', '["Sudan", "SD", "SDN"]'),
    ('SE', 'Sweden', '["Sweden", "SE", "SWE"]'),
    ('SG', 'Singapore', '["Singapore", "SG", "SGP"]'),
    ('SH', 'St. Helena', '["St. Helena", "SH", "SHN"]'),
    ('SI', 'Slovenia', '["Slovenia", "SI", "SVN"]'),
    ('SJ', 'Svalbard & Jan Mayen', '["Svalbard & Jan Mayen", "SJ", "SJM"]'),
    ('SK', 'Slovakia', '["Slovakia", "SK", "SVK"]'),
    ('SL', 'Sierra Leone', '["Sierra Leone", "SL", "SLE"]'),
    ('SM', 'San Marino', '["San Marino", "SM", "SMR"]'),
    ('SN', 'Senegal', '["Senegal", "SN", "SEN"]'),
    ('SO', 'Somalia', '["Somalia", "SO", "SOM"]'),
    ('SR', 'Suriname', '["Suriname", "SR", "SUR"]'),
    ('SS', 'South Sudan', '["South Sudan", "SS", "SSD"]'),
    ('ST', 'São Tomé & Príncipe', '["São Tomé & Príncipe", "ST", "STP"]'),
    ('SV', 'El Salvador', '["El Salvador", "SV", "SLV"]'),
    ('SX', 'Sint Maarten', '["Sint Maarten", "SX", "SXM"]'),
    ('SY', 'Syria', '["Syria", "SY", "SYR"]'),
    ('SZ', 'Eswatini', '["Eswatini", "SZ", "SWZ"]'),
    ('TC', 'Turks & Caicos Islands', '["Turks & Caicos Islands", "TC", "TCA"]'),
    ('TD', 'Chad', '["Chad", "TD", "TCD"]'),
    ('TF', 'French Southern Territories', '["French Southern Territories", "TF", "ATF"]'),
    ('TG', 'Togo', '["Togo", "TG", "TGO"]'),
    ('TH', 'Thailand', '["Thailand", "TH", "THA"]'),
    ('TJ', 'Tajikistan', '["Tajikistan", "TJ", "TJK"]'),
    ('TK', 'Tokelau', '["Tokelau", "TK", "TKL"]'),
    ('TL', 'Timor-Leste', '["Timor-Leste", "TL", "TLS"]'),
    ('TM', 'Turkmenistan', '["Turkmenistan", "TM", "TKM"]'),
    ('TN', 'Tunisia', '["Tunisia", "TN", "TUN"]'),
    ('TO', 'Tonga', '["Tonga", "TO", "TON"]'),
    ('TR', 'Türkiye', '["Türkiye", "TR", "TUR"]'),
    ('TT', 'Trinidad & Tobago', '["Trinidad & Tobago", "TT", "TTO"]'),
    ('TV', 'Tuvalu', '["Tuvalu", "TV", "TUV"]'),
    ('TW', 'Taiwan', '["Taiwan", "TW", "TWN"]'),
    ('TZ', 'Tanzania', '["Tanzania", "TZ", "TZA"]'),
    ('UA', 'Ukraine', '["Ukraine", "UA", "UKR"]'),
    ('UG', 'Uganda', '["Uganda", "UG", "UGA"]'),
    ('UM', 'U.S. Outlying Islands', '["U.S. Outlying Islands", "UM", "UMI"]'),
    ('US', 'United States', '["United States", "US", "USA"]'),
    ('UY', 'Uruguay', '["Uruguay", "UY", "URY"]'),
    ('UZ', 'Uzbekistan', '["Uzbekistan", "UZ", "UZB"]'),
    ('VA', 'Vatican City', '["Vatican City", "VA", "VAT"]'),
    ('VC', 'St. Vincent & Grenadines', '["St. Vincent & Grenadines", "VC", "VCT"]'),
    ('VE', 'Venezuela', '["Venezuela", "VE", "VEN"]'),
    ('VG', 'British Virgin Islands', '["British Virgin Islands", "VG", "VGB"]'),
    ('VI', 'U.S. Virgin Islands', '["U.S. Virgin Islands", "VI", "VIR"]'),
    ('VN', 'Vietnam', '["Vietnam", "VN", "VNM"]'),
    ('VU', 'Vanuatu', '["Vanuatu", "VU", "VUT"]'),
    ('WF', 'Wallis & Futuna', '["Wallis & Futuna", "WF", "WLF"]'),
    ('WS', 'Samoa', '["Samoa", "WS", "WSM"]'),
    ('YE', 'Yemen', '["Yemen", "YE", "YEM"]'),
    ('YT', 'Mayotte', '["Mayotte", "YT", "MYT"]'),
    ('ZA', 'South Africa', '["South Africa", "ZA", "ZAF"]'),
    ('ZM', 'Zambia', '["Zambia", "ZM", "ZMB"]'),
    ('ZW', 'Zimbabwe', '["Zimbabwe", "ZW", "ZWE"]');
