CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(320)              NOT NULL,
    password_hash VARCHAR(100)              NOT NULL,
    name          VARCHAR(255)              NOT NULL,
    role          VARCHAR(50) DEFAULT 'user' NOT NULL,
    active        BOOLEAN     DEFAULT TRUE   NOT NULL,
    created_at    TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT users_email_normalized CHECK (email = LOWER(TRIM(email)))
);

CREATE UNIQUE INDEX users_email_unique ON users (LOWER(email));

COMMENT ON COLUMN users.password_hash IS 'BCrypt password hash';
