CREATE TABLE debug_http_exchanges
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT                                NOT NULL,
    recorded_at     TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    provider        VARCHAR(100)                          NOT NULL,
    method          VARCHAR(10)                           NOT NULL,
    url             TEXT                                  NOT NULL,
    request_body    TEXT,
    status_code     INTEGER                               NOT NULL,
    response_body   TEXT,
    duration_millis BIGINT      DEFAULT 0                 NOT NULL,
    truncated       BOOLEAN     DEFAULT FALSE             NOT NULL
);

CREATE INDEX debug_http_exchanges_user_id ON debug_http_exchanges (user_id, id);

COMMENT ON TABLE debug_http_exchanges IS 'Provider traffic recorded while a user has debug recording armed. Holds whatever the provider sent, so it can contain buyer names and addresses; the debug panel clears a user''s rows on request.';
COMMENT ON COLUMN debug_http_exchanges.truncated IS 'A body longer than the stored cap was cut short';
