CREATE TABLE tenants
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(100)                          NOT NULL,
    name       VARCHAR(255)                          NOT NULL,
    active     BOOLEAN     DEFAULT TRUE              NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT tenants_code_normalized CHECK (code = LOWER(TRIM(code)))
);

CREATE UNIQUE INDEX tenants_code_unique ON tenants (code);

COMMENT ON TABLE tenants IS 'A store the portal reconciles for. A tenant owns its provider credentials, so which marketplace, gateway and accounting accounts a request reaches is decided by whose tenant is serving it.';
COMMENT ON COLUMN tenants.code IS 'Stable identifier used where a tenant is named rather than joined to, such as the default tenant setting.';

CREATE TABLE user_tenants
(
    user_id    BIGINT                                NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    tenant_id  BIGINT                                NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (user_id, tenant_id)
);

CREATE INDEX user_tenants_tenant_id ON user_tenants (tenant_id, user_id);

COMMENT ON TABLE user_tenants IS 'Which tenants a login may serve. Identity rather than tenant-owned data: it is read before a tenant is known, so it carries no automatic tenant filter and is queried by user instead.';
