CREATE TABLE bank_statement_entries
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id              BIGINT                                NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    account_iban           VARCHAR(34)                           NOT NULL,
    entry_reference        VARCHAR(140)                          NOT NULL,
    booking_date           DATE                                  NOT NULL,
    value_date             DATE,
    amount                 NUMERIC(19, 2)                        NOT NULL,
    currency               VARCHAR(3)                            NOT NULL,
    direction              VARCHAR(6)                            NOT NULL,
    status                 VARCHAR(10)                           NOT NULL,
    domain_code            VARCHAR(10),
    family_code            VARCHAR(10),
    sub_family_code        VARCHAR(10),
    proprietary_code       VARCHAR(35),
    counterparty_name      VARCHAR(255),
    counterparty_iban      VARCHAR(34),
    counterparty_bic       VARCHAR(11),
    end_to_end_id          VARCHAR(35),
    instruction_id         VARCHAR(35),
    remittance_information TEXT,
    mapping                TEXT,
    created_at             TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at             TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- What makes a re-uploaded entry the same entry. Tenant-owned tables carry the tenant in their unique constraints:
-- @TenantId keeps one tenant from reading another's rows, but two banks' customers legitimately share an entry
-- reference, and that collision is the one thing the annotation does not catch.
CREATE UNIQUE INDEX bank_statement_entries_reference_unique
    ON bank_statement_entries (tenant_id, account_iban, entry_reference);

CREATE INDEX bank_statement_entries_booking_date
    ON bank_statement_entries (tenant_id, booking_date);

COMMENT ON TABLE bank_statement_entries IS 'Booked entries of a tenant''s bank account, imported from an ISO 20022 camt.052 or camt.053 document. The bank is the one account reconciliation cannot read live, so unlike everything else it reconciles against, this is stored.';
COMMENT ON COLUMN bank_statement_entries.entry_reference IS 'The bank''s own reference for the entry, AcctSvcrRef where it states one. Re-importing a range that already landed finds its entries by this rather than inserting them again.';
COMMENT ON COLUMN bank_statement_entries.direction IS 'CREDIT or DEBIT as the document stated it. The amount is kept unsigned, the way camt states it.';
COMMENT ON COLUMN bank_statement_entries.proprietary_code IS 'The bank''s own transaction code beside the ISO domain/family pair, such as Swedbank''s IZP or INB.';
COMMENT ON COLUMN bank_statement_entries.mapping IS 'What a person wrote to tie this entry to an order when every automatic match failed. The only user-owned column here, and the one an import never overwrites.';
