CREATE TABLE job_runs
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT       NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    job_code    VARCHAR(100) NOT NULL,
    triggered_by VARCHAR(10) NOT NULL,
    outcome     VARCHAR(12)  NOT NULL,
    started_at  TIMESTAMPTZ  NOT NULL,
    finished_at TIMESTAMPTZ,
    tally       TEXT,
    failure     TEXT
);

-- What the jobs screen reads: the latest run of one job for the tenant asking, and that job's recent history under it.
CREATE INDEX job_runs_recent
    ON job_runs (tenant_id, job_code, started_at DESC);

COMMENT ON TABLE job_runs IS 'One run of one job for one tenant. A job is tenant-specific, so a scheduled firing writes a row per active tenant and a firing from the portal writes one for the tenant the caller serves. Stored rather than held in memory because a run that failed at three in the morning has to still say so in the morning.';
COMMENT ON COLUMN job_runs.triggered_by IS 'schedule or manual: whether the cron fired this run or a person did.';
COMMENT ON COLUMN job_runs.outcome IS 'running, succeeded, failed, or interrupted. A row left running by a process that stopped is closed as interrupted when the next one starts, nothing in progress surviving a restart.';
COMMENT ON COLUMN job_runs.tally IS 'What the run came to, as a JSON object of counts keyed by the job''s own codes. Codes and numbers rather than a sentence: the wording of a count lives in the portal catalogs, as a reconciliation failure''s does.';
COMMENT ON COLUMN job_runs.failure IS 'The technical account of why a run failed, as the exception stated it. A diagnostic shown as it is, not user-facing wording.';
