CREATE TABLE data_sources
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  BIGINT       NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    name       VARCHAR(200) NOT NULL,
    provider   VARCHAR(50)  NOT NULL,
    config     JSONB        NOT NULL DEFAULT '{}'::jsonb,
    enabled    BOOLEAN      NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX data_sources_tenant_name_unique ON data_sources (tenant_id, name);

COMMENT ON TABLE data_sources IS
    'A tenant''s own configured data source, e.g. one PayPal account. Tenant-owned: @TenantId is what makes it so.';
COMMENT ON COLUMN data_sources.provider IS
    'The specific provider this data source configures, e.g. PAYPAL. Each provider has its own config shape.';
COMMENT ON COLUMN data_sources.config IS
    'Provider-specific configuration, including credentials. Secret fields are individually AES-GCM encrypted (see SettingsEncryption) before being stored, so the value in this column is never a plaintext secret.';
COMMENT ON COLUMN data_sources.enabled IS
    'Whether this data source is active. A tenant can keep credentials configured but temporarily disabled.';
