CREATE TABLE provider_accounts
(
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         BIGINT       NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,
    name              VARCHAR(200) NOT NULL,
    provider          VARCHAR(50)  NOT NULL,
    config            JSONB        NOT NULL DEFAULT '{}'::jsonb,
    enabled           BOOLEAN      NOT NULL DEFAULT true,
    sort_order        INTEGER      NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX provider_accounts_tenant_name_unique ON provider_accounts (tenant_id, name);

COMMENT ON TABLE provider_accounts IS
    'A tenant''s own account with an external provider, e.g. one PayPal account. Tenant-owned: @TenantId is what makes it so.';
COMMENT ON COLUMN provider_accounts.provider IS
    'The external party this account is held with, e.g. PAYPAL. Each provider has its own config shape.';
COMMENT ON COLUMN provider_accounts.config IS
    'Provider-specific configuration, including credentials and whatever else that provider has - a marketplace config also carries the operating period bounding the orders that count. Secret fields are individually AES-GCM encrypted (see SettingsEncryption) before being stored, so the value in this column is never a plaintext secret.';
COMMENT ON COLUMN provider_accounts.enabled IS
    'Whether this account is active. A tenant can keep credentials configured but temporarily disabled.';
COMMENT ON COLUMN provider_accounts.sort_order IS
    'Where this account sits in its tenant''s own arrangement, counted from 0. Not unique: two rows sharing a position fall back to the name, so reordering never has to dodge a constraint mid-update.';
