CREATE TABLE portal_user
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(320)              NOT NULL,
    password_hash VARCHAR(100)              NOT NULL,
    name          VARCHAR(255)              NOT NULL,
    role          VARCHAR(50) DEFAULT 'user' NOT NULL,
    active        BOOLEAN     DEFAULT TRUE   NOT NULL,
    created_at    TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT portal_user_email_normalized CHECK (email = LOWER(TRIM(email)))
);

CREATE UNIQUE INDEX portal_user_email_unique ON portal_user (LOWER(email));

COMMENT ON COLUMN portal_user.password_hash IS 'BCrypt password hash';

-- Generate a hash with:
--   htpasswd -bnBC 12 "" "your-password" | tr -d ':\n'
-- Then manage users with an insert such as:
-- INSERT INTO portal_user (email, password_hash, name, role)
-- VALUES ('admin@example.com', '$2y$12$...', 'Administrator', 'admin');
