UPDATE product SET web_store ='iizii.eu' WHERE web_store = 'iizii';
UPDATE product SET web_store ='oreol.eu' WHERE web_store = 'Oreol';
UPDATE product SET web_store ='220.lv' WHERE web_store = '220';
UPDATE product SET web_store ='labsveikals.lv' WHERE web_store = 'Labs Veikals';
UPDATE product SET web_store ='babycity.lv' WHERE web_store = 'Baby City';
UPDATE product SET web_store ='balticguru.eu' WHERE web_store = 'Baltic Guru';
UPDATE product SET web_store ='rdveikals.lv' WHERE web_store = 'RD Electronic';
UPDATE product SET web_store ='barbora.lv' WHERE web_store = 'barbora';
UPDATE product SET web_store ='ksenukai.lv' WHERE web_store = 'Ksenukai';
UPDATE product SET web_store ='m79.lv' WHERE web_store = 'm79';
UPDATE product SET web_store ='xsrotallietas.lv' WHERE web_store = 'XS Rotaļlietas';
UPDATE product SET web_store ='rimi.lv' WHERE web_store = 'RIMI';
UPDATE product SET web_store ='toysplanet.lv' WHERE web_store = 'Toys Planet';
UPDATE product SET web_store ='maxtrade.lv' WHERE web_store = 'Maxtrade';
UPDATE product SET web_store ='dateks.lv' WHERE web_store = 'Dateks';
UPDATE product SET web_store ='1a.lv' WHERE web_store = '1a';
UPDATE product SET web_store ='digimart.lv' WHERE web_store = 'Digimart';
UPDATE product SET web_store ='berniem.eu' WHERE web_store = 'Berniem';
UPDATE product SET web_store ='depo.lv' WHERE web_store = 'Depo';
